### ISSUE TITLE
Use npm-run-all in your scripts

### ISSUE THREAD

**Issue by chenglabs** [MilesLin/AngularFundamentals-vNG4#1]
Nice work.
I would use npm-run-all instead of running cmd to start up json-server. Mac and linux developers would appreciate it.

install npm-run-all:
npm i npm-run-all -S

package.json:
    "scripts": {
        "ng": "ng",
        "start": "npm-run-all -p json-server ng-serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "json-server": "json-server api\\db.json --routes api\\routes.json",
        "ng-serve": "ng serve"
    },

**Comment by MilesLin** [comment]
@chenglabs thank you for the suggestion, I had modified it.
